// ============================================================
// NYKAA FASHION - DECIDE MVP : PRODUCT DATA
//
// GENERATED by build_data.py from
// tail_sku_audit_filled_corrected.csv (21 SKUs).
// Do not hand-edit: re-run the script instead.
//
// Every value here is read from that CSV. `brand` and `name` are
// parsed from the real listing URL because the dataset has no brand
// or product-name column. `category` groups the raw category string
// by keyword.
//
// buyer_photos_count is deliberately NOT carried over: buyer photos
// are not part of this MVP and must not enter confidence or UI.
//
// null means the listing does not state it. Render null as
// "Not provided" - never substitute a guess.
// ============================================================

const PRODUCTS = [
  {
    "id": "SKU01",
    "brand": "U S POLO ASSN",
    "name": "Men White Embroidered Logo Compact Cotton Polo T Shirt",
    "category": "Polo Shirts",
    "rawCategory": "polo shirt",
    "price": 1599,
    "rating": 4.5,
    "reviewCount": 1,
    "seller": "Arvind Lifestyle Brands Limited",
    "url": "https://www.nykaafashion.com/u-s-polo-assn-men-white-embroidered-logo-compact-cotton-polo-t-shirt/p/7755296",
    "attributes": {
      "fabric": "2ply compact cotton",
      "fit": "Regular",
      "measurements": null,
      "weightGsm": null,
      "careStated": true
    },
    "couldSay": "2ply compact cotton, regular fit, half sleeves and machine wash → everyday casual polo with a collar-neck construction.",
    "cannotSay": "No cotton percentage, garment measurements or fabric weight; thickness, drape and exact fit cannot be quantified.",
    "marketingAdjectives": [
      "comfortable",
      "show-stopper",
      "fun"
    ],
    "falsifiableFacts": 9,
    "descriptionWords": 50,
    "descriptionStyle": "mixed",
    "listingVerdict": "USEFUL",
    "notes": "1 written review; Men > Topwear > Polo T-Shirts. Review count and listing facts verified on the product page."
  },
  {
    "id": "SKU02",
    "brand": "TOMMY HILFIGER",
    "name": "Yellow Cotton Half Sleeves Collar Neck Polo T Shirt",
    "category": "Polo Shirts",
    "rawCategory": "polo shirt",
    "price": 2343,
    "rating": 4.4,
    "reviewCount": 1,
    "seller": "Pvh Arvind Fashion Private Limited",
    "url": "https://www.nykaafashion.com/tommy-hilfiger-yellow-cotton-half-sleeves-collar-neck-polo-t-shirt/p/24896154",
    "attributes": {
      "fabric": "Cotton",
      "fit": "Regular",
      "measurements": null,
      "weightGsm": null,
      "careStated": true
    },
    "couldSay": "Cotton, regular fit, half sleeves, collar neck, button-fly and hand wash → casual polo with a clearly stated construction.",
    "cannotSay": "No cotton percentage, garment measurements or GSM/fabric weight; 'timeless', 'stylish' and similar claims are not measurable.",
    "marketingAdjectives": [
      "cheerful",
      "classic",
      "timeless",
      "stylish",
      "fresh"
    ],
    "falsifiableFacts": 10,
    "descriptionWords": 56,
    "descriptionStyle": "marketing_led",
    "listingVerdict": "USEFUL",
    "notes": "Luxe-tagged Tommy Hilfiger polo; 1 written review. Long description is mostly lifestyle language, while structured fields carry the checkable facts."
  },
  {
    "id": "SKU03",
    "brand": "SANWARA",
    "name": "Green Stylish Ethnic Chikankari With Sequins Kurta For Men",
    "category": "Kurta",
    "rawCategory": "kurta",
    "price": 4749,
    "rating": 4.5,
    "reviewCount": 2,
    "seller": "Sanwara Fashions",
    "url": "https://www.nykaafashion.com/sanwara-green-stylish-ethnic-chikankari-with-sequins-kurta-for-men/p/16346884",
    "attributes": {
      "fabric": "Cotton",
      "fit": "Regular",
      "measurements": null,
      "weightGsm": null,
      "careStated": true
    },
    "couldSay": "Cotton, regular fit, mandarin neck, chikankari work, full sleeves and dry-clean-only care → festive embroidered kurta.",
    "cannotSay": "No fabric weight or garment measurements; softness, comfort and exact fit cannot be quantified from the listing.",
    "marketingAdjectives": [
      "Festive-Ready",
      "Exquisite"
    ],
    "falsifiableFacts": 11,
    "descriptionWords": 31,
    "descriptionStyle": "mixed",
    "listingVerdict": "USEFUL",
    "notes": "2 written reviews; Men > Ethnicwear > Kurtas."
  },
  {
    "id": "SKU04",
    "brand": "KRAFT INDIA",
    "name": "Men Black Chikankari Cotton Kurta",
    "category": "Kurta",
    "rawCategory": "kurta",
    "price": 1408,
    "rating": 4.2,
    "reviewCount": 1,
    "seller": "Aditya Global Inc",
    "url": "https://www.nykaafashion.com/kraft-india-men-black-chikankari-cotton-kurta/p/13049127",
    "attributes": {
      "fabric": "Cotton",
      "fit": "Regular",
      "measurements": null,
      "weightGsm": null,
      "careStated": true
    },
    "couldSay": "Cotton, regular fit, mandarin neck, chikankari work, full sleeves and machine wash → festive embroidered kurta.",
    "cannotSay": "No garment measurements or fabric weight; the listing does not quantify fit, thickness or fabric blend percentage.",
    "marketingAdjectives": [
      "stylish"
    ],
    "falsifiableFacts": 11,
    "descriptionWords": 43,
    "descriptionStyle": "mixed",
    "listingVerdict": "USEFUL",
    "notes": "1 written review; Men > Ethnicwear > Kurtas. The lone review also flags a fit problem, making this useful for the audit."
  },
  {
    "id": "SKU05",
    "brand": "CLUB YORK",
    "name": "Men Grey Full Sleeve Solid Notched Lapel Suit Set Set Of 2",
    "category": "Suit Sets",
    "rawCategory": "suit set",
    "price": 3000,
    "rating": 3.4,
    "reviewCount": 1,
    "seller": "York Exports Ltd",
    "url": "https://www.nykaafashion.com/club-york-men-grey-full-sleeve-solid-notched-lapel-suit-set-set-of-2/p/16415887",
    "attributes": {
      "fabric": "High-Quality Cotton",
      "fit": "Regular",
      "measurements": null,
      "weightGsm": null,
      "careStated": true
    },
    "couldSay": "Cotton, regular fit, two-piece set, notch lapel, straight leg, mid-waist trouser and gentle machine wash → formal suit set.",
    "cannotSay": "No blazer/trouser garment measurements, fabric weight or size-specific fit dimensions; 'high-quality' is not measurable from the listing.",
    "marketingAdjectives": [
      "Captivating",
      "High-Quality"
    ],
    "falsifiableFacts": 13,
    "descriptionWords": 43,
    "descriptionStyle": "mixed",
    "listingVerdict": "USEFUL",
    "notes": "1 written review; Men > Topwear > Suits. Product is currently shown sold out on the page."
  },
  {
    "id": "SKU06",
    "brand": "SNITCH",
    "name": "Beige Solid Relaxed Casual Track Pants For Men",
    "category": "Bottomwear",
    "rawCategory": "bottom wear",
    "price": 1599,
    "rating": 3.1,
    "reviewCount": 1,
    "seller": "Snitch Apparels Private Limited",
    "url": "https://www.nykaafashion.com/snitch-beige-solid-relaxed-casual-track-pants-for-men/p/20961082",
    "attributes": {
      "fabric": "Nylon; durable nylon blend",
      "fit": "Relaxed",
      "measurements": null,
      "weightGsm": null,
      "careStated": true
    },
    "couldSay": "Nylon, relaxed fit, drawstring closure, straight leg, mid waist and machine wash → casual track pant with a relaxed silhouette.",
    "cannotSay": "No nylon percentage, fabric weight or garment measurements; durability, comfort and flexibility are not quantified.",
    "marketingAdjectives": [
      "durable",
      "stylish",
      "Perfect",
      "ideal"
    ],
    "falsifiableFacts": 10,
    "descriptionWords": 29,
    "descriptionStyle": "mixed",
    "listingVerdict": "USEFUL",
    "notes": "1 written review; Men > Bottomwear > Trackpants. Review count verified from the Nykaa product listing/review page."
  },
  {
    "id": "SKU07",
    "brand": "LOUIS PHILIPPE",
    "name": "Men Purple Slim Fit Textured Full Sleeves Formal Shirt",
    "category": "Formal Shirts",
    "rawCategory": "formal shirt",
    "price": 1475,
    "rating": 4.5,
    "reviewCount": 1,
    "seller": "Westbury Holdings Private Limited",
    "url": "https://www.nykaafashion.com/louis-philippe-men-purple-slim-fit-textured-full-sleeves-formal-shirt/p/16611347",
    "attributes": {
      "fabric": "Cotton",
      "fit": "Slim",
      "measurements": null,
      "weightGsm": null,
      "careStated": true
    },
    "couldSay": "Cotton, slim fit, textured pattern, full sleeves, collar neck and machine wash → formal shirt with a clearly stated construction.",
    "cannotSay": "No garment measurements or fabric weight; 'refined sartorial taste' is marketing language rather than a checkable product property.",
    "marketingAdjectives": [
      "Refined Sartorial"
    ],
    "falsifiableFacts": 11,
    "descriptionWords": 19,
    "descriptionStyle": "marketing_led",
    "listingVerdict": "USEFUL",
    "notes": "1 written review; Men > Topwear > Formal Shirts. Description itself is almost entirely title-level language."
  },
  {
    "id": "SKU08",
    "brand": "VAN HEUSEN",
    "name": "Men Cream Slim Fit Solid Full Sleeves Formal Shirt",
    "category": "Formal Shirts",
    "rawCategory": "formal shirt",
    "price": 1265,
    "rating": 3.0,
    "reviewCount": 1,
    "seller": "Westbury Holdings Private Limited",
    "url": "https://www.nykaafashion.com/van-heusen-men-cream-slim-fit-solid-full-sleeves-formal-shirt/p/16877281",
    "attributes": {
      "fabric": "Cotton; high quality cotton",
      "fit": "Slim",
      "measurements": null,
      "weightGsm": null,
      "careStated": true
    },
    "couldSay": "Cotton, slim fit, solid pattern, full sleeves, front pocket and machine wash → conventional formal shirt construction.",
    "cannotSay": "No cotton percentage, garment measurements or fabric weight; 'high quality' and 'chic' are not measurable listing facts.",
    "marketingAdjectives": [
      "chic",
      "high quality",
      "stylish"
    ],
    "falsifiableFacts": 11,
    "descriptionWords": 44,
    "descriptionStyle": "mixed",
    "listingVerdict": "USEFUL",
    "notes": "1 written review; Men > Topwear > Formal Shirts. Structured facts materially outperform the short marketing description."
  },
  {
    "id": "SKU09",
    "brand": "JOCKEY",
    "name": "Lightweight Microfiber Solid Round Neck T Shirt Green",
    "category": "Activewear",
    "rawCategory": "activewear",
    "price": 799,
    "rating": 4.0,
    "reviewCount": 9,
    "seller": "Page Industries Ltd",
    "url": "https://www.nykaafashion.com/jockey-lightweight-microfiber-solid-round-neck-t-shirt-green/p/16600010",
    "attributes": {
      "fabric": "100% Micro Polyester",
      "fit": "Regular",
      "measurements": null,
      "weightGsm": null,
      "careStated": true
    },
    "couldSay": "100% micro polyester, regular fit, pull-on closure, half sleeves, gym & training activity and 40°C gentle-wash instructions → synthetic active T-shirt; mesh and drying claims are explicitly stated.",
    "cannotSay": "No actual garment weight, GSM or garment measurements; antimicrobial, drying and cooling performance is claimed but not quantified.",
    "marketingAdjectives": [
      "Lightweight",
      "Smartfabric",
      "unmatched",
      "StayFresh",
      "StayDry",
      "Breathable",
      "enhanced",
      "elevated",
      "Label Free"
    ],
    "falsifiableFacts": 12,
    "descriptionWords": 61,
    "descriptionStyle": "mixed",
    "listingVerdict": "USEFUL",
    "notes": "9 written reviews; Men > Active & Sports > T-Shirts & Tanks."
  },
  {
    "id": "SKU10",
    "brand": "SPYKAR",
    "name": "Black Genuine Leather Belt",
    "category": "Bags & Accessories",
    "rawCategory": "bags/accessories",
    "price": 520,
    "rating": 4.4,
    "reviewCount": 1,
    "seller": "Spykar Lifestyles Private Limited",
    "url": "https://www.nykaafashion.com/spykar-black-genuine-leather-belt/p/6580269",
    "attributes": {
      "fabric": "Genuine Leather",
      "fit": null,
      "measurements": null,
      "weightGsm": null,
      "careStated": true
    },
    "couldSay": "Leather, push-pin closure, non-reversible, not water resistant and wipe-clean care → basic leather belt with clearly stated hardware/care attributes.",
    "cannotSay": "No belt length/width or leather grade is stated; durability and exact sizing cannot be inferred.",
    "marketingAdjectives": [],
    "falsifiableFacts": 7,
    "descriptionWords": 4,
    "descriptionStyle": "spec_led",
    "listingVerdict": "USEFUL",
    "notes": "1 written review; Men > Personal Accessories > Belts. The description is only the product name, while the structured fields carry the useful specifications."
  },
  {
    "id": "SKU11",
    "brand": "U S POLO ASSN",
    "name": "Men Red Cotton Solid Polo T Shirt",
    "category": "Polo Shirts",
    "rawCategory": "Polo shirt (men)",
    "price": 1120,
    "rating": null,
    "reviewCount": null,
    "seller": "Arvind Lifestyle Brands Ltd",
    "url": "https://www.nykaafashion.com/u-s-polo-assn-men-red-cotton-solid-polo-t-shirt/p/5952525",
    "attributes": {
      "fabric": "Cotton",
      "fit": "Regular",
      "measurements": null,
      "weightGsm": null,
      "careStated": true
    },
    "couldSay": "Cotton, collar neck, half sleeves, machine-washable, single-pack - confirms material class and cut.",
    "cannotSay": "No GSM or flat garment measurements stated - cannot confirm fabric weight or exact size against body.",
    "marketingAdjectives": [
      "\"plays a leading role in the universe of clothing\"",
      "\"impeccable tailoring\"",
      "\"fine fabric that feels super soft against the skin\""
    ],
    "falsifiableFacts": 6,
    "descriptionWords": 50,
    "descriptionStyle": "mixed",
    "listingVerdict": "PARTIAL",
    "notes": "All sizes sold out at check. No SKU-level rating badge rendered (only a brand-wide 4.1/1L+ aggregate) - likely 0 reviews on this SKU but unconfirmed."
  },
  {
    "id": "SKU12",
    "brand": "SOJANYA",
    "name": "Cotton Blend Blue Checked Only Long Kurta",
    "category": "Kurta",
    "rawCategory": "Kurta for men",
    "price": 1599,
    "rating": null,
    "reviewCount": null,
    "seller": "Shri Ram Enterprises",
    "url": "https://www.nykaafashion.com/sojanya-cotton-blend-blue-checked-only-long-kurta/p/2369425",
    "attributes": {
      "fabric": "Blended Fabric",
      "fit": "Regular",
      "measurements": null,
      "weightGsm": null,
      "careStated": true
    },
    "couldSay": "Blended fabric, mandarin neck, full sleeves, slant pocket, machine-washable - confirms cut and care routine.",
    "cannotSay": "No fibre percentage, GSM, or garment measurements - cannot confirm actual fabric weight or fit.",
    "marketingAdjectives": [
      "\"Look Your Ethnic Best\"",
      "brand tagline \"(Since 1958)\" used as a quality cue"
    ],
    "falsifiableFacts": 7,
    "descriptionWords": 25,
    "descriptionStyle": "mixed",
    "listingVerdict": "PARTIAL",
    "notes": "Tagged BESTSELLER on the category page despite no visible per-SKU rating badge on the product page itself - bestseller labelling appears independent of visible review volume."
  },
  {
    "id": "SKU13",
    "brand": "MIRAVAN",
    "name": "Blue Cotton Embroidered Kurta With Palazzo",
    "category": "Kurta",
    "rawCategory": "Kurta for women",
    "price": 1680,
    "rating": 3.1,
    "reviewCount": 113,
    "seller": "Tirupati Alloys",
    "url": "https://www.nykaafashion.com/miravan-blue-cotton-embroidered-kurta-with-palazzo/p/26852992",
    "attributes": {
      "fabric": "Cotton",
      "fit": "Straight",
      "measurements": null,
      "weightGsm": null,
      "careStated": true
    },
    "couldSay": "Cotton, V-neck, three-quarter sleeves, wide-leg palazzo - confirms silhouette and neckline.",
    "cannotSay": "No fibre %, GSM, or measurements - cannot confirm fabric weight or actual garment fit.",
    "marketingAdjectives": [
      "\"Your Ethnic Wear Collection Is Incomplete without This Kurta Set\"",
      "\"Features An Elegant Hue Which Makes It A Must-Have\""
    ],
    "falsifiableFacts": 6,
    "descriptionWords": 30,
    "descriptionStyle": "marketing_led",
    "listingVerdict": "PARTIAL",
    "notes": "NOT a tail SKU - 113 ratings is well over the <20 threshold; slipped through because it carried no BESTSELLER tag on the listing page. Recommend swapping. Sold as a 2-piece kurta+palazzo set, not a standalone kurta."
  },
  {
    "id": "SKU14",
    "brand": "RAJNANDINI",
    "name": "Green Cotton Blend Printed Ready To Wear Kurta With Salwar And Dupatta",
    "category": "Suit Sets",
    "rawCategory": "Suit set for women",
    "price": 799,
    "rating": 3.3,
    "reviewCount": 22,
    "seller": "Rajnandini Fashion India Ltd",
    "url": "https://www.nykaafashion.com/rajnandini-green-cotton-blend-printed-ready-to-wear-kurta-with-salwar-and-dupatta/p/26184406",
    "attributes": {
      "fabric": "Cotton Blend",
      "fit": "Regular",
      "measurements": null,
      "weightGsm": null,
      "careStated": true
    },
    "couldSay": "Cotton blend, round neck, tapered-leg salwar bottoms, hand-wash only - confirms cut and a real care constraint.",
    "cannotSay": "No GSM or flat measurements - cannot confirm fabric weight or exact size.",
    "marketingAdjectives": [
      "\"Steal the limelight in this stunning green salwar suit\"",
      "\"amp up your look\""
    ],
    "falsifiableFacts": 7,
    "descriptionWords": 40,
    "descriptionStyle": "marketing_led",
    "listingVerdict": "PARTIAL",
    "notes": "Borderline tail: 22 star-ratings (just above the <20 cutoff) but zero written reviews or photos visible - ratings volume without any qualitative signal behind it."
  },
  {
    "id": "SKU15",
    "brand": "BENE KLEED",
    "name": "Men Cream Pure Cotton Rigid Denim Jeans",
    "category": "Bottomwear",
    "rawCategory": "Bottom wear for men",
    "price": 2999,
    "rating": 3.9,
    "reviewCount": 14,
    "seller": "Shakti Brandz Pvt Ltd",
    "url": "https://www.nykaafashion.com/bene-kleed-men-cream-pure-cotton-rigid-denim-jeans/p/24997127",
    "attributes": {
      "fabric": "Cotton",
      "fit": "Loose",
      "measurements": null,
      "weightGsm": null,
      "careStated": true
    },
    "couldSay": "100% cotton, non-stretch, wide-leg, machine washable - confirms fabric type and fit category.",
    "cannotSay": "No denim weight/GSM or flat measurements - cannot tell how heavy/stiff the denim is or exact waist/inseam.",
    "marketingAdjectives": [
      "\"unmatched comfort and style\"",
      "\"breathable and versatile\"",
      "\"effortless charm\""
    ],
    "falsifiableFacts": 7,
    "descriptionWords": 35,
    "descriptionStyle": "marketing_led",
    "listingVerdict": "PARTIAL",
    "notes": "Genuinely tail (14 ratings) - clean example of a real low-review SKU."
  },
  {
    "id": "SKU16",
    "brand": "VBEAUTI",
    "name": "Womens Washed Grey Wide Leg Streachable High Rise Jeans",
    "category": "Bottomwear",
    "rawCategory": "Bottom wear for women",
    "price": 1155,
    "rating": null,
    "reviewCount": null,
    "seller": "Smvd Enterprises",
    "url": "https://www.nykaafashion.com/vbeauti-womens-washed-grey-wide-leg-streachable-high-rise-jeans/p/28439251",
    "attributes": {
      "fabric": "Denim",
      "fit": "Wide",
      "measurements": null,
      "weightGsm": null,
      "careStated": true
    },
    "couldSay": "Stretch denim, high-rise wide-leg, and an unusually detailed 7-step wash/care instruction - confirms fit category and care routine precisely.",
    "cannotSay": "No GSM or flat garment measurements - cannot confirm denim weight or exact waist/inseam size.",
    "marketingAdjectives": [
      "\"flattering fit\"",
      "\"Trendy wide-leg silhouette\"",
      "\"Premium washed\"",
      "\"Soft",
      "durable",
      "and comfortable\""
    ],
    "falsifiableFacts": 9,
    "descriptionWords": 35,
    "descriptionStyle": "marketing_led",
    "listingVerdict": "PARTIAL",
    "notes": "No rating badge at all - tagged \"New on Nykaa\", the strongest 0-review signal found in this audit. Care instructions here are the most detailed (7 discrete steps) of any SKU checked."
  },
  {
    "id": "SKU17",
    "brand": "BUYNEWTREND",
    "name": "Yellow Women Striped Wrap Style Cotton Shirt",
    "category": "Formal Shirts",
    "rawCategory": "Formal shirt for women",
    "price": 705,
    "rating": 4.4,
    "reviewCount": 10,
    "seller": "Dimpy Garments",
    "url": "https://www.nykaafashion.com/buynewtrend-yellow-women-striped-wrap-style-cotton-shirt/p/25737100",
    "attributes": {
      "fabric": "Cotton",
      "fit": "Regular",
      "measurements": null,
      "weightGsm": null,
      "careStated": true
    },
    "couldSay": "Cotton, striped pattern, collar neck, cap sleeves, gentle wash - all from the spec table alone.",
    "cannotSay": "No GSM or measurements, and the free-text description adds ZERO new checkable facts beyond the spec table - it's a single unbroken run of ~20 adjectives with no numbers.",
    "marketingAdjectives": [
      "\"Elegant women cotton shirt\"",
      "\"lightweight comfort\"",
      "\"summer friendly\"",
      "\"modern fit\"",
      "\"soft texture\"",
      "\"skin friendly material\"",
      "\"versatile styling\"",
      "\"durable stitching\"",
      "\"easy care\"",
      "\"everyday fashion essential\"",
      "\"premium quality tailored silhouette trendy timeless classic chic appeal\""
    ],
    "falsifiableFacts": 7,
    "descriptionWords": 45,
    "descriptionStyle": "marketing_led",
    "listingVerdict": "PARTIAL",
    "notes": "Best example in the set of pure marketing substitution: the description is essentially a keyword-stuffed adjective list ending in 'premium quality tailored silhouette trendy timeless classic chic appeal.' Genuinely tail (10 ratings)."
  },
  {
    "id": "SKU18",
    "brand": "COLUMBIA",
    "name": "Men Black Na Heavyweight Ii Tight",
    "category": "Activewear",
    "rawCategory": "Activewear for men",
    "price": 4499,
    "rating": null,
    "reviewCount": null,
    "seller": "Chogori India Retail Ltd",
    "url": "https://www.nykaafashion.com/columbia-men-black-na-heavyweight-ii-tight/p/9044405",
    "attributes": {
      "fabric": "Polyester",
      "fit": "Regular",
      "measurements": null,
      "weightGsm": null,
      "careStated": true
    },
    "couldSay": "Polyester, skinny-leg tights, machine washable, built for Sports & Fitness activity - confirms material class and cut.",
    "cannotSay": "The product NAME invokes Columbia's 'Omni-Heat Reflective' thermal technology, but nothing in the actual listing explains what that means, what GSM the fabric is, or how warm it performs - the tech claim is completely unsubstantiated in the copy.",
    "marketingAdjectives": [
      "\"comfy addition\"",
      "\"premium quality fabric\"",
      "\"exude a regular fit\""
    ],
    "falsifiableFacts": 6,
    "descriptionWords": 25,
    "descriptionStyle": "marketing_led",
    "listingVerdict": "PARTIAL",
    "notes": "Small category (12 items total under men's Athleisure) - mostly winter/thermal gear rather than gym wear. No rating badge shown - likely 0 reviews."
  },
  {
    "id": "SKU19",
    "brand": "KICA",
    "name": "Float Green Jumpsuit With Pockets",
    "category": "Activewear",
    "rawCategory": "Activewear for women",
    "price": 1258,
    "rating": null,
    "reviewCount": null,
    "seller": "Nykaa Fashion Ltd",
    "url": "https://www.nykaafashion.com/kica-float-green-jumpsuit-with-pockets/p/3234152",
    "attributes": {
      "fabric": "Cotton-95%, Spandex-5%",
      "fit": "\"Stretchy without being saggy\" (informal, no structured Fit field)",
      "measurements": null,
      "weightGsm": null,
      "careStated": true
    },
    "couldSay": "95% cotton / 5% spandex is an exact, checkable fibre blend (rare on this platform); halter neck, sleeveless, cold hand-wash only, two pockets, back-neck button closure.",
    "cannotSay": "No GSM or flat body measurements - still cannot confirm fabric weight or exact fit against the body.",
    "marketingAdjectives": [
      "\"make your float effortlessly through life\"",
      "\"Extra soft feel\"",
      "\"butter-soft cotton\""
    ],
    "falsifiableFacts": 8,
    "descriptionWords": 110,
    "descriptionStyle": "mixed",
    "listingVerdict": "USEFUL",
    "notes": "Best fibre-composition example found - an exact percentage split, unusual for Nykaa listings generally. No returns/exchange allowed on this item. No rating badge - likely 0 reviews."
  },
  {
    "id": "SKU20",
    "brand": "HARISSONS",
    "name": "Unisex Dexter Maroon Backpack",
    "category": "Bags & Accessories",
    "rawCategory": "Bags/accessories for men",
    "price": 1999,
    "rating": 4.3,
    "reviewCount": 7,
    "seller": "Haridas Somchand And Sons",
    "url": "https://www.nykaafashion.com/harissons-unisex-dexter-maroon-backpack/p/15717995",
    "attributes": {
      "fabric": "Polyester",
      "fit": "N/A",
      "measurements": "(H x L x W) 50 x 39 x 6 cm",
      "weightGsm": null,
      "careStated": true
    },
    "couldSay": "50x39x6cm, fits laptops up to 14 inches, water resistant, 1-year warranty, external USB port and audio-jack routing - all genuinely checkable claims a buyer could hold the seller to on arrival.",
    "cannotSay": "'Meticulously built to withstand the test of time' and 'endure various forms of abuse' are not backed by any durability rating, denier count, or load-test figure in the listing.",
    "marketingAdjectives": [
      "\"captivating Vintage Collection\"",
      "\"delightful 90s VIBE\"",
      "\"meticulously built to withstand the test of time\"",
      "\"exceptional build quality is a given\"",
      "\"endure various forms of abuse\"",
      "\"reliable companion for every adventure\""
    ],
    "falsifiableFacts": 10,
    "descriptionWords": 230,
    "descriptionStyle": "mixed",
    "listingVerdict": "USEFUL",
    "notes": "Highest falsifiable-fact density of any SKU in this audit (exact dimensions + laptop-size compatibility + warranty length + water resistance) despite having the single most adjective-heavy description text found. Genuinely tail (7 ratings)."
  },
  {
    "id": "SKU21",
    "brand": "YELLOE",
    "name": "Blue Heart Shaped Sling Bag",
    "category": "Bags & Accessories",
    "rawCategory": "Bags/accessories for women",
    "price": 896,
    "rating": 4.1,
    "reviewCount": 104,
    "seller": "Yelloe Lifestyle Pvt Ltd",
    "url": "https://www.nykaafashion.com/yelloe-blue-heart-shaped-sling-bag/p/19029743",
    "attributes": {
      "fabric": "Table says \"Cotton\"; description says \"Premium synthetic leather\" (contradiction)",
      "fit": "N/A",
      "measurements": "(L x B x H): 15.2 x 5 x 13.2 cm",
      "weightGsm": null,
      "careStated": true
    },
    "couldSay": "15.2 x 5 x 13.2cm, zip closure, detachable strap, 3-month warranty - real checkable dimensions and a stated warranty term.",
    "cannotSay": "The spec table says the material is 'Cotton'; the free-text description says 'Premium synthetic leather.' The listing contradicts itself, so the tool cannot tell a buyer what the bag is actually made of.",
    "marketingAdjectives": [
      "\"adorable\"",
      "\"catch everyone's eye\"",
      "\"versatile as can be\"",
      "\"functional yet playful\"",
      "\"emitting Valentine's Day vibes - a curious charmer\"",
      "\"keeps you looking trendy and organized\""
    ],
    "falsifiableFacts": 6,
    "descriptionWords": 65,
    "descriptionStyle": "mixed",
    "listingVerdict": "USEFUL",
    "notes": "NOT a tail SKU - 104 ratings is well over the <20 threshold; recommend swapping. Flagged because it's the clearest material-contradiction case found: structured field and marketing copy disagree outright."
  }
];
